### ISSUE TITLE
on click of image , its is not opening , like tap or something

### ISSUE THREAD

**Issue by amithit** [google-business-communications/nodejs-businessmessages#2]
i am using this json to send media , but when i click on that image , not able to open it.
var richcard = {

      standaloneCard:{
        cardContent: {
          'media': {
            'contentInfo': {
              'forceRefresh': true,
              'fileUrl': 'https://storage.googleapis.com/sample-logos/sf-office.png',
            },
            'height': 'TALL',
          }
        }
      }
    }
     sendResponse({
      messageId: uuidv4(),
      representative:getRepresentative(agentDetails),

      richCard: richcard
    }, conversationId,agentDetails);
  }

**Comment by thefalc** [comment]
With a rich card, you can't tap on the image and make it bigger. If you want that behavior, you can send an image on it's own using this approach: https://developers.google.com/business-communications/business-messages/guides/build/send#images

Sean

**Comment by amithit** [comment]
Thanks @thefalc
